name: Azure Bicep Infra

on: [push, workflow_dispatch]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Lint Bicep code 
    - name: Run Bicep linter
      run: az bicep build --file ./main.bicep

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Development'
    steps:

      # Checkout code
    - uses: actions/checkout@main
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file to Development environment
    - name: Deploy to Dev
      uses: azure/arm-deploy@v1
      with:
        app-name: 'talphaidze-app-dev-bicep'
        slot-name: 'Production'

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: 'Production'
    steps:

      # Checkout code
    - uses: actions/checkout@main
      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file to Production environment
    - name: Deploy to Prod
      uses: azure/arm-deploy@v1
      with:
        app-name: 'talphaidzeappprodbicep'
        slot-name: 'Production'
